// <auto-generated />
using System;
using FlashCards.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlashCards.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210407140840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlashCards.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Correct = false,
                            CreationTimeStamp = new DateTime(2021, 4, 7, 14, 8, 39, 404, DateTimeKind.Utc).AddTicks(4040),
                            DeckId = 1,
                            Definition = "A tool for learning",
                            Term = "Flashcard"
                        },
                        new
                        {
                            CardId = 2,
                            Correct = false,
                            CreationTimeStamp = new DateTime(2021, 4, 7, 14, 8, 39, 404, DateTimeKind.Utc).AddTicks(9553),
                            DeckId = 1,
                            Definition = "A tool for losing",
                            Term = "Poker Card"
                        },
                        new
                        {
                            CardId = 3,
                            Correct = false,
                            CreationTimeStamp = new DateTime(2021, 4, 7, 14, 8, 39, 404, DateTimeKind.Utc).AddTicks(9695),
                            DeckId = 2,
                            Definition = "A tool for living",
                            Term = "Insurance card"
                        });
                });

            modelBuilder.Entity("FlashCards.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeckDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeckName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            CreationTimeStamp = new DateTime(2021, 4, 7, 14, 8, 39, 402, DateTimeKind.Utc).AddTicks(558),
                            DeckDescription = "Seed Deck",
                            DeckName = "Seed Deck"
                        },
                        new
                        {
                            DeckId = 2,
                            CreationTimeStamp = new DateTime(2021, 4, 7, 14, 8, 39, 404, DateTimeKind.Utc).AddTicks(2010),
                            DeckDescription = "Seed Deck 2",
                            DeckName = "Seed Deck 2"
                        });
                });

            modelBuilder.Entity("FlashCards.Models.Card", b =>
                {
                    b.HasOne("FlashCards.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("FlashCards.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
